### ISSUE TITLE
Netrify上で環境変数の設定をする。

### ISSUE THREAD

**Issue by teruto725** [CodeParty2021/code_party_front#12]
Netrify上での環境変数が設定できていないので動作しない。
いっそのことcodepartyアカウントでnetrifyアカウントを作ってそっちでホスティングしても良いかも

**Comment by teruto725** [comment]
動作が完了するところまで確認してほしい

**Comment by iikyara** [comment]
設定完了！

**Comment by teruto725** [comment]
確認できました。publishマージしておきました。

**Comment by teruto725** [comment]
注意としてpr内で動作確認するときはfirebaseの設定でドメインを追加する必要があります。
![image](https://user-images.githubusercontent.com/45113742/156744728-97c0b6cd-b0ab-4189-badc-29a32436bfb4.png)
