### ISSUE TITLE
hot reloadが出来なくなるバグ

### ISSUE THREAD

**Issue by iikyara** [CodeParty2021/code_party_front#21]
### 現象
- ファイル保存時に自動リロードされない
- エラーオーバーレイが出ない
- ホットリロード時にこんな感じのエラーが出る
![image](https://user-images.githubusercontent.com/26971566/156873070-2e562882-4f43-4a37-81b4-6c9d76415450.png)

### 調査
- react-scripts v4がオーバーレイモジュールと競合しているらしい
  - https://qreat.tech/2536/
  - https://github.com/facebook/create-react-app/issues/11771

### 対策
- react-scripts v5にバージョンアップする。
```
yarn add --exact react-scripts@5.0.0
```
- もしくはreact-error-overlayをバージョン6.0.9に固定する。
```
yarn add react-error-overlay@6.0.9

/// package.jsonに以下を追加
"resolutions": {
  "react-error-overlay": "6.0.9"
},
```

**Comment by teruto725** [comment]
ホットリロード確認できました！
クローズOKです。
お疲れ様！
