### ISSUE TITLE
招待URLをOGBに対応させたい（プレビューが表示されるようにしたい）

### ISSUE THREAD

**Issue by teruto725** [CodeParty2021/code_party_front#30]
OGBとはリンクを貼り付けたときに表示されるプレビューのこと。
SPAだと難しいらしい...

<img width="549" alt="image" src="https://user-images.githubusercontent.com/45113742/160293116-44c61e0a-8af0-4f43-945f-79e3d1ece3f4.png">

**Comment by iikyara** [comment]
Netlifyのpre-rendering機能で解決できそう

- なんとなくまとめ
  - SPAでOGRを上手く表示できない原因
    - ORGはjavascriptを動かさない。（htmlファイルのみを取得）
  - netlifyのPre-rendering
    - 事前にjavascriptを実行してページごとにレンダリングする
    - ヘッダーのmeta情報はreact-helmetあたりを使って動的に設定
  - これでOGR対応できそう？？
- 参考
  - https://qiita.com/rentama/items/1d6d5bde441653efbc37

**Comment by teruto725** [comment]
おー良さそう！
